service: worldpay-payments-gateway-app

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  memorySize: 128

functions:
  app:
    handler: ./dist/serverless.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

plugins:
  - serverless-offline